import { Substats } from "./objects";
import { MainStats } from "./objects";
export const _PossibleRolls: Record<Substats, number[]> = {
  [Substats.HP]: [209.13, 239.0, 268.88, 298.75],
  [Substats.HP_]: [4.08, 4.66, 5.25, 5.83],
  [Substats.ATK]: [13.62, 15.56, 17.51, 19.45],
  [Substats.ATK_]: [4.08, 4.66, 5.25, 5.83],
  [Substats.DEF]: [16.2, 18.52, 20.83, 23.15],
  [Substats.DEF_]: [5.1, 5.83, 6.56, 7.29],
  [Substats.CDMG_]: [5.44, 6.22, 6.99, 7.77],
  [Substats.CRATE_]: [2.72, 3.11, 3.5, 3.89],
  [Substats.EM]: [16.32, 18.65, 20.98, 23.31],
  [Substats.ER_]: [4.53, 5.18, 5.83, 6.48],
};

export const _DomainIdsToSetIds: Record<number, number[]> = {
  //Midsummer courtyard (Thundering fury and Thundersoother)
  1: [1.1, 1.2],
  //Valley of Remembrance (Viridescent Venerer and Maiden Beloved)
  2: [2.1, 2.2],
  //Domain of Guyun (Archaic Petra and Retracing Bolide)
  3: [3.1, 3.2],
  //Hidden Palace of Zhou Formula (Crimson Witch of Flames and Lavawalker)
  4: [4.1, 4.2],
  //Clear Pool and Mountain Cavern (Noblesse Oblige and Bloodstained Chivalry)
  5: [5.1, 5.2],
  //Peak of Vindagnyr (Blizzard Strayer and Heart of Depth)
  6: [6.1, 6.2],
  //Ridge Watch (Tenacity of the Milelith and Pale flame)
  7: [7.1, 7.2],
  //Momiji-Dyed Court (Emblem of Severed Fate and Shimenawa's Reminiscence)
  8: [8.1, 8.2],
  //Slumbering Court (Husk of Opulent Dreams and Ocean hued Clam)
  9: [9.1, 9.2],
  //The Lost Valley (Vermillion Hereafter and Echoes of an Offering)
  10: [10.1, 10.2],
  //Spire of Solitary Enlightenment (Deepwood Memories and Gilded Dreams)
  11: [11.1, 11.2],
  //City of Gold (Flower of Paradise Lost and Desert Pavilion Chronicle)
  12: [12.1, 12.2],
  //Molten Iron Fortress (Nymph's Dreams and Vorukasha's Glow)
  13: [13.1, 13.2],
};

export const _DomainIdToName: Record<number, string> = {
  1: "Midsummer courtyard (thundering fury and thundersoother)",
  2: "Valley of Remembrance (Viridescent Venerer and Maiden Beloved)",
  3: "Domain of Guyun (Archaic Petra and Retracing Bolide)",
  4: "Hidden Palace of Zhou Formula (Crimson Witch of Flames and Lavawalker)",
  5: "Clear Pool and Mountain Cavern (Noblesse Oblige and Bloodstained Chivalry)",
  6: "Peak of Vindagnyr (Blizzard Strayer and Heart of Depth)",
  7: "Ridge Watch (Tenacity of the Milelith and Pale flame)",
  8: "Momiji-Dyed Court (Emblem of Severed Fate and Shimenawa's Reminiscence)",
  9: "Slumbering Court (Husk of Opulent Dreams and Ocean hued Clam)",
  10: "The Lost Valley (Vermillion Hereafter and Echoes of an Offering)",
  11: "Spire of Solitary Enlightenment (Deepwood Memories and Gilded Dreams)",
  12: "City of Gold (Flower of Paradise Lost and Desert Pavilion Chronicle)",
  13: "Molten Iron Fortress (Nymph's Dreams and Vorukasha's Glow)",
};

export const _SetIdToName: Record<number, string> = {
  1.1: "Thundering fury",
  1.2: "Thundersoother",
  2.1: "Viridescent Venerer",
  2.2: "Maiden Beloved",
  3.1: "Archaic Petra",
  3.2: "Retracing Bolide",
  4.1: "Crimson Witch Of Flames",
  4.2: "Lavawalker",
  5.1: "Noblesse Oblige",
  5.2: "Bloodstained Chivalry",
  6.1: "Blizzard Strayer",
  6.2: "Heart Of Depth",
  7.1: "Tenacity Of The Milelith",
  7.2: "Pale Flame",
  8.1: "Emblem Of Severed Fate",
  8.2: "Shimenawa's Reminiscence",
  9.1: "Husk Of Opulent Dreams",
  9.2: "Ocean Hued Clam",
  10.1: "Vermillion Hereafter",
  10.2: "Echoes Of An Offering",
  11.1: "Deepwood Memories",
  11.2: "Gilded Dreams",
  12.1: "Flower Of Paradise Lost",
  12.2: "Desert Pavilion Chronicle",
  13.1: "Nymph's Dreams",
  13.2: "Vorukasha's Glow",
};
export const _MainStatsToPossibleSubStats: Record<MainStats, Substats[]> = {
  [MainStats.HP]: [
    Substats.HP_,
    Substats.ATK,
    Substats.ATK_,
    Substats.DEF,
    Substats.DEF_,
    Substats.EM,
    Substats.ER_,
    Substats.CRATE_,
    Substats.CDMG_,
  ],
  [MainStats.ATK]: [
    Substats.HP_,
    Substats.HP,
    Substats.ATK_,
    Substats.DEF,
    Substats.DEF_,
    Substats.EM,
    Substats.ER_,
    Substats.CRATE_,
    Substats.CDMG_,
  ],
  [MainStats.ATK_]: [
    Substats.HP,
    Substats.HP_,
    Substats.ATK,
    Substats.DEF,
    Substats.DEF_,
    Substats.EM,
    Substats.ER_,
    Substats.CRATE_,
    Substats.CDMG_,
  ],
  [MainStats.HP_]: [
    Substats.HP,
    Substats.ATK,
    Substats.ATK_,
    Substats.DEF,
    Substats.DEF_,
    Substats.EM,
    Substats.ER_,
    Substats.CRATE_,
    Substats.CDMG_,
  ],
  [MainStats.DEF_]: [
    Substats.HP,
    Substats.HP_,
    Substats.ATK,
    Substats.ATK_,
    Substats.DEF,
    Substats.EM,
    Substats.ER_,
    Substats.CRATE_,
    Substats.CDMG_,
  ],
  [MainStats.EM]: [
    Substats.HP,
    Substats.HP_,
    Substats.ATK,
    Substats.ATK_,
    Substats.DEF,
    Substats.DEF_,
    Substats.ER_,
    Substats.CRATE_,
    Substats.CDMG_,
  ],
  [MainStats.ER_]: [
    Substats.HP,
    Substats.HP_,
    Substats.ATK,
    Substats.ATK_,
    Substats.DEF,
    Substats.DEF_,
    Substats.EM,
    Substats.CRATE_,
    Substats.CDMG_,
  ],
  [MainStats.CRATE_]: [
    Substats.HP,
    Substats.HP_,
    Substats.ATK,
    Substats.ATK_,
    Substats.DEF,
    Substats.DEF_,
    Substats.EM,
    Substats.ER_,
    Substats.CDMG_,
  ],
  [MainStats.CDMG_]: [
    Substats.HP,
    Substats.HP_,
    Substats.ATK,
    Substats.ATK_,
    Substats.DEF,
    Substats.DEF_,
    Substats.EM,
    Substats.ER_,
    Substats.CRATE_,
  ],
  [MainStats.HEAL_]: [
    Substats.HP,
    Substats.HP_,
    Substats.ATK,
    Substats.ATK_,
    Substats.DEF,
    Substats.DEF_,
    Substats.EM,
    Substats.ER_,
    Substats.CRATE_,
    Substats.CDMG_,
  ],
  [MainStats.DendroDMG_]: [
    Substats.HP,
    Substats.HP_,
    Substats.ATK,
    Substats.ATK_,
    Substats.DEF,
    Substats.DEF_,
    Substats.EM,
    Substats.ER_,
    Substats.CRATE_,
    Substats.CDMG_,
  ],
  [MainStats.ElectroDMG_]: [
    Substats.HP,
    Substats.HP_,
    Substats.ATK,
    Substats.ATK_,
    Substats.DEF,
    Substats.DEF_,
    Substats.EM,
    Substats.ER_,
    Substats.CRATE_,
    Substats.CDMG_,
  ],
  [MainStats.PyroDMG_]: [
    Substats.HP,
    Substats.HP_,
    Substats.ATK,
    Substats.ATK_,
    Substats.DEF,
    Substats.DEF_,
    Substats.EM,
    Substats.ER_,
    Substats.CRATE_,
    Substats.CDMG_,
  ],
  [MainStats.HydroDMG_]: [
    Substats.HP,
    Substats.HP_,
    Substats.ATK,
    Substats.ATK_,
    Substats.DEF,
    Substats.DEF_,
    Substats.EM,
    Substats.ER_,
    Substats.CRATE_,
    Substats.CDMG_,
  ],
  [MainStats.AnemoDMG_]: [
    Substats.HP,
    Substats.HP_,
    Substats.ATK,
    Substats.ATK_,
    Substats.DEF,
    Substats.DEF_,
    Substats.EM,
    Substats.ER_,
    Substats.CRATE_,
    Substats.CDMG_,
  ],
  [MainStats.GeoDMG_]: [
    Substats.HP,
    Substats.HP_,
    Substats.ATK,
    Substats.ATK_,
    Substats.DEF,
    Substats.DEF_,
    Substats.EM,
    Substats.ER_,
    Substats.CRATE_,
    Substats.CDMG_,
  ],
  [MainStats.CryoDMG_]: [
    Substats.HP,
    Substats.HP_,
    Substats.ATK,
    Substats.ATK_,
    Substats.DEF,
    Substats.DEF_,
    Substats.EM,
    Substats.ER_,
    Substats.CRATE_,
    Substats.CDMG_,
  ],
  [MainStats.PhysDMG_]: [
    Substats.HP,
    Substats.HP_,
    Substats.ATK,
    Substats.ATK_,
    Substats.DEF,
    Substats.DEF_,
    Substats.EM,
    Substats.ER_,
    Substats.CRATE_,
    Substats.CDMG_,
  ],
};
export const _TypeToPossibleMainStats: Record<string, MainStats[]> = {
  sands: [
    MainStats.DEF_,
    MainStats.HP_,
    MainStats.ATK_,
    MainStats.EM,
    MainStats.ER_,
  ],
  goblet: [
    MainStats.HP_,
    MainStats.ATK_,
    MainStats.DEF_,
    MainStats.EM,
    MainStats.DendroDMG_,
    MainStats.ElectroDMG_,
    MainStats.PyroDMG_,
    MainStats.CryoDMG_,
    MainStats.HydroDMG_,
    MainStats.AnemoDMG_,
    MainStats.GeoDMG_,
    MainStats.PhysDMG_,
  ],
  circlet: [
    MainStats.HP_,
    MainStats.ATK_,
    MainStats.DEF_,
    MainStats.EM,
    MainStats.CDMG_,
    MainStats.CRATE_,
    MainStats.HEAL_,
  ],
};

//main stat values from Lvl 1 to Lvl 20
export const _MainStatsLevelValues: Record<MainStats, number[]> = {
  [MainStats.HP]: [717, 4780],
  [MainStats.HP_]: [7.0, 46.6],
  [MainStats.ATK]: [47, 311],
  [MainStats.ATK_]: [7.0, 46.6],
  [MainStats.DEF_]: [8.7, 58.3],
  [MainStats.EM]: [28, 186.5],
  [MainStats.ER_]: [7.8, 51.8],
  [MainStats.CRATE_]: [4.7, 31.1],
  [MainStats.CDMG_]: [9.3, 62.2],
  [MainStats.AnemoDMG_]: [7.0, 46.6],
  [MainStats.PyroDMG_]: [7.0, 46.6],
  [MainStats.ElectroDMG_]: [7.0, 46.6],
  [MainStats.HydroDMG_]: [7.0, 46.6],
  [MainStats.GeoDMG_]: [7.0, 46.6],
  [MainStats.CryoDMG_]: [7.0, 46.6],
  [MainStats.DendroDMG_]: [7.0, 46.6],
  [MainStats.HEAL_]: [5.4, 35.9],
  [MainStats.PhysDMG_]: [8.7, 58.3],
};

export const MainStatTypeToSubStatChances = {
  "sands": {
    [MainStats.HP_]: {
      [Substats.HP]: 0.15,
      [Substats.ATK]: 0.15,
      [Substats.DEF]: 0.15,
      [Substats.ATK_]: 0.1,
      [Substats.DEF_]: 0.1,
      [Substats.EM]: 0.1,
      [Substats.ER_]: 0.1,
      [Substats.CRATE_]: 0.075,
      [Substats.CDMG_]: 0.075,
    },
    [MainStats.ATK_]: {
      [Substats.HP]: 0.15,
      [Substats.ATK]: 0.15,
      [Substats.DEF]: 0.15,
      [Substats.HP_]: 0.1,
      [Substats.DEF_]: 0.1,
      [Substats.EM]: 0.1,
      [Substats.ER_]: 0.1,
      [Substats.CRATE_]: 0.075,
      [Substats.CDMG_]: 0.075,
    },
    [MainStats.DEF_]: {
      [Substats.HP]: 0.15,
      [Substats.ATK]: 0.15,
      [Substats.DEF]: 0.15,
      [Substats.HP_]: 0.1,
      [Substats.ATK_]: 0.1,
      [Substats.EM]: 0.1,
      [Substats.ER_]: 0.1,
      [Substats.CRATE_]: 0.075,
      [Substats.CDMG_]: 0.075,
    },
    [MainStats.EM]: {
      [Substats.HP]: 0.15,
      [Substats.ATK]: 0.15,
      [Substats.DEF]: 0.15,
      [Substats.HP_]: 0.1,
      [Substats.ATK_]: 0.1,
      [Substats.DEF_]: 0.1,
      [Substats.ER_]: 0.1,
      [Substats.CRATE_]: 0.075,
      [Substats.CDMG_]: 0.075,
    },
    [MainStats.ER_]: {
      [Substats.HP]: 0.15,
      [Substats.ATK]: 0.15,
      [Substats.DEF]: 0.15,
      [Substats.HP_]: 0.1,
      [Substats.ATK_]: 0.1,
      [Substats.DEF_]: 0.1,
      [Substats.EM]: 0.1,
      [Substats.CRATE_]: 0.075,
      [Substats.CDMG_]: 0.075,
    },
  },
  "goblet": {
    [MainStats.HP_]: {
      [Substats.HP]: 0.15,
      [Substats.ATK]: 0.15,
      [Substats.DEF]: 0.15,
      [Substats.ATK_]: 0.1,
      [Substats.DEF_]: 0.1,
      [Substats.EM]: 0.1,
      [Substats.ER_]: 0.1,
      [Substats.CRATE_]: 0.075,
      [Substats.CDMG_]: 0.075,
    },
    [MainStats.ATK_]: {
      [Substats.HP]: 0.15,
      [Substats.ATK]: 0.15,
      [Substats.DEF]: 0.15,
      [Substats.HP_]: 0.1,
      [Substats.DEF_]: 0.1,
      [Substats.EM]: 0.1,
      [Substats.ER_]: 0.1,
      [Substats.CRATE_]: 0.075,
      [Substats.CDMG_]: 0.075,
    },
    [MainStats.DEF_]: {
      [Substats.HP]: 0.15,
      [Substats.ATK]: 0.15,
      [Substats.DEF]: 0.15,
      [Substats.HP_]: 0.1,
      [Substats.ATK_]: 0.1,
      [Substats.EM]: 0.1,
      [Substats.ER_]: 0.1,
      [Substats.CRATE_]: 0.075,
      [Substats.CDMG_]: 0.075,
    },
    [MainStats.DendroDMG_]: {
      [Substats.HP]: 0.1364,
      [Substats.ATK]: 0.1364,
      [Substats.DEF]: 0.1364,
      [Substats.HP_]: 0.0909,
      [Substats.DEF_]: 0.0909,
      [Substats.EM]: 0.0909,
      [Substats.ER_]: 0.0909,
      [Substats.CRATE_]: 0.0682,
      [Substats.CDMG_]: 0.0682,
    },
    [MainStats.PyroDMG_]: {
      [Substats.HP]: 0.1364,
      [Substats.ATK]: 0.1364,
      [Substats.DEF]: 0.1364,
      [Substats.HP_]: 0.0909,
      [Substats.DEF_]: 0.0909,
      [Substats.EM]: 0.0909,
      [Substats.ER_]: 0.0909,
      [Substats.CRATE_]: 0.0682,
      [Substats.CDMG_]: 0.0682,
    },
    [MainStats.CryoDMG_]: {
      [Substats.HP]: 0.1364,
      [Substats.ATK]: 0.1364,
      [Substats.DEF]: 0.1364,
      [Substats.HP_]: 0.0909,
      [Substats.DEF_]: 0.0909,
      [Substats.EM]: 0.0909,
      [Substats.ER_]: 0.0909,
      [Substats.CRATE_]: 0.0682,
      [Substats.CDMG_]: 0.0682,
    },
    [MainStats.HydroDMG_]: {
      [Substats.HP]: 0.1364,
      [Substats.ATK]: 0.1364,
      [Substats.DEF]: 0.1364,
      [Substats.HP_]: 0.0909,
      [Substats.DEF_]: 0.0909,
      [Substats.EM]: 0.0909,
      [Substats.ER_]: 0.0909,
      [Substats.CRATE_]: 0.0682,
      [Substats.CDMG_]: 0.0682,
    },
    [MainStats.ElectroDMG_]: {
      [Substats.HP]: 0.1364,
      [Substats.ATK]: 0.1364,
      [Substats.DEF]: 0.1364,
      [Substats.HP_]: 0.0909,
      [Substats.DEF_]: 0.0909,
      [Substats.EM]: 0.0909,
      [Substats.ER_]: 0.0909,
      [Substats.CRATE_]: 0.0682,
      [Substats.CDMG_]: 0.0682,
    },
    [MainStats.GeoDMG_]: {
      [Substats.HP]: 0.1364,
      [Substats.ATK]: 0.1364,
      [Substats.DEF]: 0.1364,
      [Substats.HP_]: 0.0909,
      [Substats.DEF_]: 0.0909,
      [Substats.EM]: 0.0909,
      [Substats.ER_]: 0.0909,
      [Substats.CRATE_]: 0.0682,
      [Substats.CDMG_]: 0.0682,
    },
    [MainStats.AnemoDMG_]: {
      [Substats.HP]: 0.1364,
      [Substats.ATK]: 0.1364,
      [Substats.DEF]: 0.1364,
      [Substats.HP_]: 0.0909,
      [Substats.DEF_]: 0.0909,
      [Substats.EM]: 0.0909,
      [Substats.ER_]: 0.0909,
      [Substats.CRATE_]: 0.0682,
      [Substats.CDMG_]: 0.0682,
    },
    [MainStats.PhysDMG_]: {
      [Substats.HP]: 0.1364,
      [Substats.ATK]: 0.1364,
      [Substats.DEF]: 0.1364,
      [Substats.HP_]: 0.0909,
      [Substats.DEF_]: 0.0909,
      [Substats.EM]: 0.0909,
      [Substats.ER_]: 0.0909,
      [Substats.CRATE_]: 0.0682,
      [Substats.CDMG_]: 0.0682,
    },
    [MainStats.EM]: {
      [Substats.HP]: 0.15,
      [Substats.ATK]: 0.15,
      [Substats.DEF]: 0.15,
      [Substats.HP_]: 0.1,
      [Substats.ATK_]: 0.1,
      [Substats.DEF_]: 0.1,
      [Substats.ER_]: 0.1,
      [Substats.CRATE_]: 0.075,
      [Substats.CDMG_]: 0.075,
    },
  },
  "circlet": {
    [MainStats.HP_]: {
      [Substats.HP]: 0.15,
      [Substats.ATK]: 0.15,
      [Substats.DEF]: 0.15,
      [Substats.ATK_]: 0.1,
      [Substats.DEF_]: 0.1,
      [Substats.EM]: 0.1,
      [Substats.ER_]: 0.1,
      [Substats.CRATE_]: 0.075,
      [Substats.CDMG_]: 0.075,
    },
    [MainStats.ATK_]: {
      [Substats.HP]: 0.15,
      [Substats.ATK]: 0.15,
      [Substats.DEF]: 0.15,
      [Substats.HP_]: 0.1,
      [Substats.DEF_]: 0.1,
      [Substats.EM]: 0.1,
      [Substats.ER_]: 0.1,
      [Substats.CRATE_]: 0.075,
      [Substats.CDMG_]: 0.075,
    },
    [MainStats.DEF_]: {
      [Substats.HP]: 0.15,
      [Substats.ATK]: 0.15,
      [Substats.DEF]: 0.15,
      [Substats.HP_]: 0.1,
      [Substats.ATK_]: 0.1,
      [Substats.EM]: 0.1,
      [Substats.ER_]: 0.1,
      [Substats.CRATE_]: 0.075,
      [Substats.CDMG_]: 0.075,
    },
    [MainStats.EM]: {
      [Substats.HP]: 0.15,
      [Substats.ATK]: 0.15,
      [Substats.DEF]: 0.15,
      [Substats.HP_]: 0.1,
      [Substats.ATK_]: 0.1,
      [Substats.DEF_]: 0.1,
      [Substats.ER_]: 0.1,
      [Substats.CRATE_]: 0.075,
      [Substats.CDMG_]: 0.075,
    },
    [MainStats.CRATE_]: {
      [Substats.HP]: 0.1463,
      [Substats.ATK]: 0.1463,
      [Substats.DEF]: 0.1463,
      [Substats.HP_]: 0.0976,
      [Substats.ATK_]: 0.0976,
      [Substats.DEF_]: 0.0976,
      [Substats.ER_]: 0.0976,
      [Substats.EM]: 0.0976,
      [Substats.CDMG_]: 0.0732,
    },
    [MainStats.CDMG_]: {
      [Substats.HP]: 0.1463,
      [Substats.ATK]: 0.1463,
      [Substats.DEF]: 0.1463,
      [Substats.HP_]: 0.0976,
      [Substats.ATK_]: 0.0976,
      [Substats.DEF_]: 0.0976,
      [Substats.ER_]: 0.0976,
      [Substats.EM]: 0.0976,
      [Substats.CRATE_]: 0.0732,
    },
    [MainStats.HEAL_]: {
      [Substats.HP]: 0.1364,
      [Substats.ATK]: 0.1364,
      [Substats.DEF]: 0.1364,
      [Substats.HP_]: 0.0909,
      [Substats.ATK_]: 0.0909,
      [Substats.DEF_]: 0.0909,
      [Substats.ER_]: 0.0909,
      [Substats.EM]: 0.0909,
      [Substats.CRATE_]: 0.0682,
      [Substats.CDMG_]: 0.0682,
    },
  },
  "flower": {
    [MainStats.HP]: {
      [Substats.ATK]: 0.1579,
      [Substats.DEF]: 0.1579,
      [Substats.HP_]: 0.1053,
      [Substats.ATK_]: 0.1053,
      [Substats.DEF_]: 0.1053,
      [Substats.EM]: 0.1053,
      [Substats.ER_]: 0.1053,
      [Substats.CRATE_]: 0.0789,
      [Substats.CDMG_]: 0.0789,
    },
  },
  "feather": {
    [MainStats.ATK]: {
      [Substats.ATK]: 0.1579,
      [Substats.DEF]: 0.1579,
      [Substats.HP_]: 0.1053,
      [Substats.ATK_]: 0.1053,
      [Substats.DEF_]: 0.1053,
      [Substats.EM]: 0.1053,
      [Substats.ER_]: 0.1053,
      [Substats.CRATE_]: 0.0789,
      [Substats.CDMG_]: 0.0789,
    },
  },
} as unknown as Record<string, Record<MainStats, Record<Substats, number>>>;